# Generated by Django 3.2.12 on 2023-02-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriescounter_app', '0002_food_item_gredient_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item_gredient',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food_item_gredient',
            name='carbs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food_item_gredient',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food_item_gredient',
            name='protein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food_item_gredient',
            name='suger',
            field=models.IntegerField(),
        ),
    ]
